import 'package:offline_first_app_flutter_demo/core/database/app_database.dart';
import 'package:offline_first_app_flutter_demo/core/enums/billing_cycles.dart';
import 'package:offline_first_app_flutter_demo/features/subscriptions/data/local/subscriptions_dao.dart';
import 'package:offline_first_app_flutter_demo/features/subscriptions/data/mappers/subscription_mapper.dart';
import 'package:offline_first_app_flutter_demo/features/subscriptions/domain/entities/subscription.dart';

/// The only entry point the UI uses for subscription data.
/// It speaks in domain entities (`Subscription`) and hides Drift types
/// (`SubscriptionRow`, `SubscriptionsCompanion`) from the UI.
///
/// Methods are added alongside the DAO queries, step by step:
/// READ (Step 2) ✅, CREATE (Step 3) ✅, DELETE (Step 4) ✅, UPDATE (Step 5) ✅.
class SubscriptionRepository {
  SubscriptionRepository(this._dao);

  final SubscriptionsDao _dao;

  // ───────────────────────── READ ─────────────────────────

  /// LIVE list of subscriptions for the UI.
  ///
  /// The DAO stream emits `List<SubscriptionRow>`; `.map` converts every
  /// emission into `List<Subscription>`. It is still a live stream: each time
  /// Drift re-emits, the conversion runs again.
  Stream<List<Subscription>> watchAll() {
    return _dao.watchAll().map(
      (rows) => rows.map((row) => row.toEntity()).toList(),
    );
  }

  // ───────────────────────── CREATE ───────────────────────

  /// Saves a new subscription locally (works offline — no network involved).
  ///
  /// Takes plain values rather than a `Subscription`, because a new
  /// subscription has no id yet: the table generates it (UUID).
  ///
  /// `SubscriptionsCompanion.insert(...)` is Drift's generated constructor
  /// for inserts: columns without a default are *required* parameters, so
  /// forgetting e.g. `price` is a compile error, not a runtime crash.
  Future<void> create({
    required String name,
    required BillingCycles billingCycle,
    required DateTime dueDate,
    required String category,
    required double price,
  }) {
    return _dao.insertSubscription(
      SubscriptionsCompanion.insert(
        name: name,
        billingCycle: billingCycle,
        dueDate: dueDate,
        category: category,
        price: price,
        // id → not given → generated by clientDefault in the table.
      ),
    );
  }

  // ───────────────────────── UPDATE ───────────────────────

  /// Saves changes to an existing subscription.
  ///
  /// Takes a full `Subscription` (unlike `create`): it already has an id,
  /// which tells the DAO which row to change. The mapper turns the entity
  /// into a Companion.
  ///
  /// Throws if no row was changed (it was deleted meanwhile), so the UI
  /// can tell the user instead of pretending it saved.
  Future<void> update(Subscription subscription) async {
    final changedRows = await _dao.updateSubscription(
      subscription.id,
      subscription.toCompanion(),
    );
    if (changedRows == 0) {
      throw StateError('Subscription no longer exists');
    }
  }

  // ───────────────────────── DELETE ───────────────────────

  /// Removes a subscription from the user's point of view.
  ///
  /// Always a SOFT delete in this offline-first app: the row is only flagged,
  /// so the deletion can be synced to the server later (Part 4).
  /// The UI doesn't need to know that detail — it just calls `delete`.
  Future<void> delete(String id) => _dao.softDelete(id);
}

/// Convenience for wiring without a DI framework:
/// `db.subscriptionRepository` instead of
/// `SubscriptionRepository(db.subscriptionsDao)`.
extension AppDatabaseRepositories on AppDatabase {
  SubscriptionRepository get subscriptionRepository =>
      SubscriptionRepository(subscriptionsDao);
}
