import 'package:drift/drift.dart';
import 'package:offline_first_app_flutter_demo/core/database/app_database.dart';
import 'package:offline_first_app_flutter_demo/features/subscriptions/data/remote/subscription_dto.dart';
import 'package:offline_first_app_flutter_demo/features/subscriptions/domain/entities/subscription.dart';

// ---------------------------------------------------------------------------
// Drift row <-> domain entity mapping
// ---------------------------------------------------------------------------
//
// Why map at all? `SubscriptionRow` is generated by Drift and changes whenever
// the table changes (e.g. sync columns in Part 4). The UI only knows our own
// `Subscription` entity, so database changes never ripple into widgets.

/// READ direction: database row → entity (used by Step 2).
extension SubscriptionRowX on SubscriptionRow {
  Subscription toEntity() => Subscription(
    id: id,
    name: name,
    billingCycle: billingCycle,
    dueDate: dueDate,
    category: category,
    price: price,
  );
}

/// WRITE direction: entity → Companion (used by Step 5, UPDATE).
///
/// Every field the entity has is wrapped in `Value(...)` = "set this column".
/// Columns the entity doesn't know about (`isDeleted`) are left out, which
/// means `Value.absent()` = "don't touch this column". So updating a
/// subscription can never accidentally un-delete it.
extension SubscriptionX on Subscription {
  SubscriptionsCompanion toCompanion() => SubscriptionsCompanion(
    id: Value(id),
    name: Value(name),
    billingCycle: Value(billingCycle),
    dueDate: Value(dueDate),
    category: Value(category),
    price: Value(price),
  );
}

// ---------------------------------------------------------------------------
// Drift row <-> server DTO mapping (sync, Part 4)
// ---------------------------------------------------------------------------

/// PUSH direction: local row → what we send to the server.
extension SubscriptionRowSyncX on SubscriptionRow {
  SubscriptionDto toDto() => SubscriptionDto(
    id: id,
    name: name,
    price: price,
    billingCycle: billingCycle,
    nextPaymentDate: dueDate, // the server calls the due date nextPaymentDate
    category: category,
    updatedAt: updatedAt,
  );
}

/// PULL direction: server version → local row to store.
extension SubscriptionDtoX on SubscriptionDto {
  /// [isSynced] is true for data FROM the server: the server already has
  /// exactly this version, so there's nothing to push back.
  ///
  /// All columns are set (not `Value.absent()`), because the server's copy
  /// replaces the local one completely.
  SubscriptionsCompanion toCompanion({bool isSynced = true}) =>
      SubscriptionsCompanion(
        id: Value(id),
        name: Value(name),
        billingCycle: Value(billingCycle),
        dueDate: Value(nextPaymentDate),
        category: Value(category),
        price: Value(price),
        isDeleted: Value(isDeleted),
        updatedAt: Value(updatedAt),
        isSynced: Value(isSynced),
      );
}
